[package]
name = "move_mania"
version = "1.0.0"
authors = []

[addresses]
move_mania = "0xBEEF"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "randomnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
