[package]
name = "zion"
version = "1.0.0"
authors = []

[addresses]
zion = "ef6d14f0984b999c358d67950e1ab211c762aac7fc0432f0947dbcfcbb749f1c"
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"

[dev-addresses]
zion = "0xBEEF"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
