[package]
name = "zion"
version = "1.0.0"
authors = []

[addresses]
zion = "_"
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"

[dev-addresses]
zion = "0xBEEF"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
